# Generated by Django 4.2 on 2023-10-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_saves_alter_save_user_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
